# Generated by Django 3.1 on 2020-08-18 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_house_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='teneant',
            name='aadhar_no',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teneant',
            name='docs',
            field=models.FileField(null=True, upload_to='rent_docs'),
        ),
        migrations.AddField(
            model_name='teneant',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='teneant',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='house.house'),
        ),
        migrations.AddField(
            model_name='teneant',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teneant',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='teneant',
            name='previous_address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='teneant',
            name='total_members',
            field=models.IntegerField(null=True),
        ),
    ]
