# Generated by Django 3.1 on 2020-08-18 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_auto_20200818_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='amount_paid',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='balance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='month',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='paid_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='teneant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='house.teneant'),
        ),
        migrations.AddField(
            model_name='rent',
            name='type_of_payment',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='year',
            field=models.DateField(null=True),
        ),
    ]
